const A = () => startScript('A')
const B = () => startScript('B')
const C1 = () => startScript('C1')
const C2 = () => startScript('C2')
const D1 = () => startScript('D1')
const D2 = () => startScript('D2')
const D3 = () => startScript('D3')
